### ISSUE TITLE
Add .gitignore Files

### ISSUE THREAD

**Issue by Hinny** [Hinny/strange-eons-xwing-plug-in#45]
As a Developer I want to add .gitignore files to the project to avoid checking in seproject and test files.

**Comment by Hinny** [comment]
Add seproject.template files if the repo is cloned for the first time they need to copy the seproject.template files and name them seproject. Add note in the installation wiki how to do this.

For the test folders do the following: Check if .gitignore is deleted by the clear folder script? If so I must change that script.

Then create a .gitignore file inside that directory that contains four lines:

```
# Ignore everything in this directory
*
# Except this file
!.gitignore
```

**Comment by Hinny** [comment]
https://github.com/Hinny/strange-eons-xwing-plug-in/wiki/Developing-the-X
‐wing-Plug‐in

Follow the 3rd point in setup.

After this initial setup, you don't have to think about it anymore.

Den 14 feb 2018 00:21 skrev "kalhamaar" <notifications@github.com>:

**Comment by kalhamaar** [comment]
Ok got it :P
