### ISSUE TITLE
Add Support for Wave 12-13

### ISSUE THREAD

**Issue by Hinny** [Hinny/strange-eons-xwing-plug-in#47]
- [x] Bulls eye arc
- [x] Reload action
- [x] Sheathipede-class shuttle icons and stats
- [x] Alpha-class Star Wing icons and stats
- [x] M12-L Kimogila Fighter icons and stats
- [x] TIE Silencer icons and stats
- [x] B/SF-17 Bomber icons and stats

**Comment by Hinny** [comment]
Use https://github.com/geordanr/xwing-miniatures-font to update x-wing fonts.

**Comment by kalhamaar** [comment]
can I do ?

**Comment by Hinny** [comment]
Yes, of course! That would be great!

**Comment by kalhamaar** [comment]
I think I did:
![selection_003](https://user-images.githubusercontent.com/19990489/36067587-13bd6cdc-0ec0-11e8-8732-78fb379fa03e.png)

PS: I fixed the jumpmaster because no more astromech nor torpedoe due to last FAQ ...

**Comment by Hinny** [comment]
Excellent! I much appreciate your contributions to this plug-in! You are on fire :)

Now, if you feel you are finished and have pushed all commit to the branch, you can create a pull request (code/branches then click on "New pull request"- button next to your branch). It is a opportunity for me and others to give feedback before the branch is merged to master.

**Comment by kalhamaar** [comment]
argh you closed too quickly, I have an issue with gitignore after rebase and forgot to fix large ship bullseye
